# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- goarch:
    - amd64
    - 386
  binary: gitmoji
archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:

release:
  draft: true
  github:
    owner: jamesdobson
    name: gogitmoji
brews:
  - name: gogitmoji
    github:
      owner: jamesdobson
      name: homebrew-gogitmoji
    url_template: "https://github.com/jamesdobson/gogitmoji/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: gogitmoji
      email: gogitmoji@softwarepunk.com
    folder: Formula
    homepage: "https://github.com/jamesdobson/gogitmoji"
    description: "gogitmoji helps you write git commit messages containing gitmoji!"
